### ISSUE TITLE
Any chance we get Binance U.S added to the csv writer?

### ISSUE THREAD

**Issue by sixniks** [alleyway/add-tradingview-alerts-tool#41]
I know the pairs are really close but having it be one to one would be really nice

**Comment by sixniks** [comment]
Also there are a bunch of missing pairs on the US version of binance, so it would help a ton so we wouldnt have to sort through the  missing pairs in the csv. Thanks for the script its pretty incredible!

**Comment by mlake** [comment]
Hi - thanks for reporting. Can you give an example of which pairs are missing?
BinanceUS does indeed have far fewer trading pairs than Binance, but perhaps I'm missing something...the two API endpoints the script talks to operate identically, but BinanceUS has fewer pairs because the US is more regulated

https://api.binance.us/api/v3/exchangeInfo
 
https://api.binance.com/api/v3/exchangeInfo

**Comment by mlake** [comment]
Why doesn't the following command work for you? Please be as detailed as possible, otherwise I'll need to close this issue.
```
    npm run fetch:binanceus all
```

**Comment by ricardodacosta** [comment]
the command npm run fetch:binanceus all does pull all coins from Binance.US perhaps @sixniks was using fetch:binance instead

**Comment by mlake** [comment]
I've updated the project a lot and changed the command syntax. I'd re-install with the new instructions which is much more user-friendly (no git checkout required)

closing this for now...
